
library(quantmod)
library(xts)
library(forecast)
library(TTR)
library(zoo)
library(tseries)


unmploy<- read.csv("C:/Users/cheru/OneDrive/Desktop/SAC420_GROUP13_PROJECT - Copy/thesis_1/multiTimeline.csv")
unmployd<-ts(unmploy,start=c(2004,1),f=12)
plot(unmployd,ylab="Jobs search",main='Time plot:Kenya Google trends jobs index ')
AY<-decompose(unmployd)
plot(AY)
DY<-diff(unmployd)
plot(DY ,ylab="Jobs search",main='Time plot:Kenya Google trends jobs index ')
adf.test(DY)
acf(DY,main="")
pacf(DY,main="")
fit_arima<-auto.arima(unmployd,d=1,D=1,stepwise=FALSE,trace=TRUE)
print(summary(fit_arima))
checkresiduals(fit_arima)
fcst<-forecast(fit_arima,h=24)
autoplot(fcst,ylab="")
print(summary(fcst))
